GENRE_ORDER = [
    'Ambient',
    'Electronic',
    'Drum & Bass',
    'Techno',
    'House',
    'Disco',
    'Hip-Hop',
    'Soul',
    'Pop',
    'Rock',
    'Alternative',
    'Folk',
    'Country',
    'World',
    'Reggae',
    'Latin',
    'Jazz',
    'Soundtrack',
    'Classical',
    'Other',
]

GENRE_MAP = {
    # Drum and Bass
    "Drum & Bass": "Drum & Bass",
    "Drum & Bass - Experimental": "Drum & Bass",
    "Drum & Bass / Jungle": "Drum & Bass",
    "Electronic: Jungle": "Drum & Bass",
    "Electronic: Drum & Bass": "Drum & Bass",
    "Dance - Drum & Bass": "Drum & Bass",
    "Drum & Bass - Jungle" : "Drum & Bass",
    "Ram Drum & Bass": "Drum & Bass",
    "dance - drum & bass / jungle": "Drum & Bass",
    "jungle": "Drum & Bass",
    "ragga jungle": "Drum & Bass",
    "footwork": "Drum & Bass",
    "juke": "Drum & Bass",

    # Techno
    "Dance - Techno": "Techno",
    "Electronic: Techno": "Techno",
    "Techno/House": "Techno",
    "Techno": "Techno",
    "Techno/Electronica": "Techno",
    "electronic - techno": "Techno",
 
    # House
    "House": "House",
    "Dance - House": "House",
    "Dance - Deep House": "House",
    "Dance - Bass House": "House",
    "Electronic - Electro House": "House",
    "house - deep": "House",
    "house - afro": "House",
    "house - soulful": "House",
    "house - disco": "House",
    "afro house": "House",
    "dance - afro house": "House",
    "amapiano": "House",
    "gqom": "House",
 
    # Electronic
    "Dance": "Electronic",
    "Dance - Garage / Bassline / Grime": "Electronic",
    "Dance - House - Dub": "Electronic",
    "Dance | Electro": "Electronic",
    "Dance/Electronic": "Electronic",
    "Dubstep": "Electronic",
    "Dubstep & Grime": "Electronic",
    "Electro": "Electronic",
    "Electronic": "Electronic",
    "Electronic - Electronica / Downtempo": "Electronic",
    "Electronic/Trip Hop": "Electronic",
    "Electronic: Electronica": "Electronic",
    "Electronica": "Electronic",
    "Elektro": "Electronic",
    "Grime": "Electronic",
    "electronica": "Electronic",
    "Garage": "Electronic",
    "Electronic: Electro": "Electronic",
    "Dance & Electronic (Dance/Techno/Disco)": "Electronic",
    "Dub": "Electronic",
    "Electronic/Dance": "Electronic",
    "Breaks & Beats": "Electronic",
    "Breaks & Beats - Electro": "Electronic",
    "electronic": "Electronic",
    "idm": "Electronic",
    "breaks":"Electronic",
    "electronic: others...": "Electronic",
    "deconstructed club":"Electronic",
    "trance": "Electronic",
    "psytrance": "Electronic",
    "progressive trance": "Electronic",
    "uplifting trance": "Electronic",
    "dance - electro": "Electronic",
    "dance - breaks": "Electronic",
    "glitch hop": "Electronic",
    "electronic: dance": "Electronic",
    "electro|dance": "Electronic",
    "electronica/dance": "Electronic",
    "bass": "Electronic",
 
    # Ambient
    "Ambient": "Ambient",
    "Electronic - Ambient": "Ambient",
    "Leftfield & Chill Out": "Ambient",
    "Lounge": "Ambient",
    "New Age": "Ambient",
    "Experimental": "Ambient",
    "Electronic - Experimental / Noise": "Ambient",
    "ambient": "Ambient",
    "Electronic: Ambient": "Ambient",
    "Leftfield & Chill Out - Ambient": "Ambient",
    "Leftfield & Chill Out - Downtempo": "Ambient",
    "Chill Out/Trip-Hop/Lounge": "Ambient",
    "Experimental...": "Ambient",
    "noise": "Ambient",
    "Easy Listening": "Ambient",
    "dance - down beat / trip hop": "Ambient",
    "sound collage": "Ambient",
    "vaporwave": "Ambient",
    "slushwave": "Ambient",
 
    # Rock
    "Alternative/Punk": "Rock",
    "Hard Rock": "Rock",
    "Metal": "Rock",
    "Metal - Hard Rock": "Rock",
    "Metal/Hard Rock": "Rock",
    "Metal/HardRock": "Rock",
    "Metalli": "Rock",
    "Psychedelic": "Rock",
    "Punk": "Rock",
    "Rock": "Rock",
    "Rock - Psychedelic": "Rock",
    "Industrial/Noise": "Rock",
    "Rock - Progressive": "Rock",
    "progressive rock": "Rock", 
    "black metal": "Rock",
    "doom metal": "Rock",
    "death metal": "Rock",
    "sludge": "Rock",
    "heavy metal": "Rock",
    "thrash metal": "Rock",
    "grindcore": "Rock",
    "stoner rock": "Rock",
    "stoner metal": "Rock",
    "stoner": "Rock",
    "doom": "Rock",
    "funeral doom metal": "Rock",
    "metalcore": "Rock",
    "power metal": "Rock",
    "brutal death metal": "Rock",
    "atmospheric black metal": "Rock",
    "post-metal": "Rock",
    "hardcore": "Rock",
    "hardcore punk": "Rock",
    "emo": "Rock",
    "psychedelic rock": "Rock",
    "garage rock": "Rock",
    "post-rock": "Rock",
    "classic rock": "Rock",
    "pop - rock: rock": "Rock",
    "blues": "Rock",
    "delta blues": "Rock",
    "classic blues": "Rock",
 
    # Alternative
    "post-punk": "Alternative",
    "Alternative|Indie Pop|Indie Rock|Pop": "Alternative",
    "Indie": "Alternative",
    "Indie Pop": "Alternative",
    "Indie Pop/Folk": "Alternative",
    "Indie Rock": "Alternative",
    "Electro Pop/Electro Rock": "Alternative",
    "Rock indÃ©": "Alternative",
    "Pop IndÃ©": "Alternative",
    "Alternative": "Alternative",
    "Alternative Rock": "Alternative",
    "Vaihtoehtoinen": "Alternative",
    "Indie Rock/Rock pop": "Alternative",
    "Alternative|Electro": "Alternative",
    "Alternative/Indie": "Alternative",
    "alternative": "Alternative",
    "Pop - Rock: Alternative - Indie": "Alternative",
    "Alternative - Indie Pop": "Alternative",
    "Indie Dance": "Alternative",
    "alternative - indie rock": "Alternative",
    "pop - alternative": "Alternative",
    "new wave": "Alternative",
    "alternative/indie italiana": "Alternative",
 
    # Pop
    "Pop": "Pop",
    "Pop - R&B": "Pop",
    "Pop Rock": "Pop",
    "Vocal": "Pop",
    "POP": "Pop",
    "Pop - Rock": "Pop",
    "Pop - Italo": "Pop",
    "synthpop": "Pop",
    "adult contemporary": "Pop",
    "french pop": "Pop",
    "french pop: french pop": "Pop",
    "pop/rock italiano": "Pop",
    "variã©tã© franã§aise": "Pop",
    "variété française": "Pop",
 
    # Disco
    "Soul & Funk": "Disco",
    "Funk": "Disco",
    "Disco": "Disco",
    "dance - nu disco / disco": "Disco",
    "r&b/soul - disco": "Disco",
 
    # Soul
    "Contemporary R&B": "Soul",
    "Contemporary Soul": "Soul",
    "Soul": "Soul",
    "R & B": "Soul",
    "R&B": "Soul",
    "R&B/Soul": "Soul",
    "R&B/Soul - Contemporary": "Soul",
    "R&B/Soul - Funk & Soul": "Soul",
    "R&B/Soul/Funk": "Soul",
    "contemporary": "Soul",
    "funk / soul": "Soul",
    "soul / funk: soul": "Soul",
    "gospel": "Soul",
 
    # Hip-Hop
    "Dirty South": "Hip-Hop",
    "Hip Hop": "Hip-Hop",
    "Hip Hop/Rap": "Hip-Hop",
    "Rap": "Hip-Hop",
    "Rap/Hip Hop": "Hip-Hop",
    "Rap/Hip-Hop": "Hip-Hop",
    "Urban": "Hip-Hop",
    "Hip-Hop/Rap": "Hip-Hop",
    "Hip Hop / Rap": "Hip-Hop",
    "Hip Hop/Rap - French Hip Hop": "Hip-Hop",
    "Hip-hop/Rap": "Hip-Hop",
    "hip hop/rap - uk hip hop": "Hip-Hop",
    "hip hop: rap / hip hop": "Hip-Hop",
    "experimental hip hop": "Hip-Hop",
    "chopped and screwed": "Hip-Hop",
    "deconstructed trap": "Hip-Hop",
    "lo-fi": "Hip-Hop",
 
    # Reggae
    "Dancehall": "Reggae",
    "Dancehall/Ragga": "Reggae",
    "REGGAE/SKA": "Reggae",
    "Reggae": "Reggae",
    "Central America/Carribean": "Reggae",
    "Reggae/Ska": "Reggae",
    "Bachata": "Reggae",
    "Reggae: Reggae": "Reggae",
 
    # Latin
    "mpb": "Latin",
    "Alternativo & Rock Latino": "Latin",
    "Latin": "Latin",
    "Latin / Tropical": "Latin",
    "Latin Musik": "Latin",
    "Latinalainen musiikki": "Latin",
    "Latino": "Latin",
    "RaÃ­ces": "Latin",
    "Brazil": "Latin",
    "Musique brÃ©silienne": "Latin",
    "South America": "Latin",
    "Brasilianische Musik": "Latin",
    "Latin Urban": "Latin",
    "Brazilian": "Latin",
    "Latin Music": "Latin",
    "brazilian - mpb": "Latin",
    "brazilian music": "Latin",
    "bossa nova": "Latin",
    "latin pop": "Latin",
 
    # Jazz
    "Instrumental jazz": "Jazz",
    "Jazz": "Jazz",
    "Jazz: Free Jazz": "Jazz",
    "Jazz: Electro Jazz": "Jazz",
    "Jazz - World": "Jazz",
    "jazz: contemporary jazz":"Jazz",
    "jazz - contemporary": "Jazz",
    "jazz - classic": "Jazz",
    "jazz - jazz funk": "Jazz",
    "jazz - nu jazz / acid jazz": "Jazz",
    "jazz - fusion": "Jazz",

    # Classical
    "Church Organ": "Classical",
    "Classical": "Classical",
    "Neo-Classical": "Classical",
    "Classique": "Classical",
    "Classical - Baroque": "Classical",
    "contemporary classical": "Classical",
    "classical crossover": "Classical",
 
    # Soundtrack
    "Film Scores": "Soundtrack",
    "Films/Games": "Soundtrack",
    "Score/Romance": "Soundtrack",
    "Soundtracks": "Soundtrack",
    "SOUNDTRACKS/CAST ALBUMS": "Soundtrack",
    "soundtrack": "Soundtrack",
    "video game music": "Soundtrack",
    "game": "Soundtrack",
    "soundtracks: movie soundtracks": "Soundtrack",
    "soundtracks: video games": "Soundtrack",
    "musiques de films": "Soundtrack",
    "films/jeux vidã©o": "Soundtrack",
    "films/jeux vidéo": "Soundtrack",
 
    # Folk
    "Folk": "Folk",
    "Singer-Songwriter": "Folk",
    "Singer-Songwriter / Folk : Contemporary Folk": "Folk",
    "Singer/Songwriter": "Folk",
    "Singer & Songwriter": "Folk",
    "Singer / Songwriter": "Folk",
 
    # Country
    "Country": "Country",
 
    # World
    "african - afrobeat": "World",
    "Africa": "World",
    "African": "World",
    "Afro-Beat": "World",
    "Asian Music": "World",
    "Musique arabe": "World",
    "World": "World",
    "World Music": "World",
    "World Music / Regional Folklore - Ethnic": "World",
    "Musique asiatique": "World",
    "World Music / Regional Folklore": "World",
    "World Music/Ethno": "World",
    "Afrikkalainen musiikki": "World",
    "African Music": "World",
    "Musique africaine": "World",
    "japanese": "World",
    "world music: africa": "World",
    "world music: maghreb": "World",
    "world music: world - fusion - others...": "World",
    "arabic": "World",
    "arabic pop": "World",
    "afrobeats": "World",
 
    # Other
    "Anime": "Other",
    "Comedy": "Other",
    "Holiday": "Other",
    "j-pop": "Other",
    "spoken word": "Other",
    "karaoke": "Other",
    "christian": "Other",
    "k-pop": "Other",
}


# Case-insensitive index of every GENRE_MAP key
_CI = {k.lower(): v for k, v in GENRE_MAP.items()}

# Aliases: common Last.fm spellings 
_ALIAS = {
    "hip-hop": "Hip-Hop",
    "hip hop": "Hip-Hop",
    "trap": "Hip-Hop",
    "rnb": "Soul",
    "r'n'b": "Soul",
    "rhythm and blues": "Soul",
    "neo-soul": "Soul",
    "neo soul": "Soul",
    "alternative rock": "Alternative",
    "indie pop": "Alternative",
    "indietronica": "Alternative",
    "shoegaze": "Alternative",
    "glitch pop": "Alternative",
    "idm": "Electronic",
    "downtempo": "Ambient",
    "chillout": "Ambient",
    "chill out": "Ambient",
    "trip-hop": "Ambient",
    "trip hop": "Ambient",
    "drone": "Ambient",
    "smooth jazz": "Jazz",
    "deep house": "House",
    "tech house": "House",
    "drum and bass": "Drum & Bass",
    "dnb": "Drum & Bass",
    "singer-songwriter": "Folk",
    "folk": "Folk",
    "reggae": "Reggae",
    "ska": "Reggae",
    "reggaeton": "Reggae",
    "dembow": "Reggae",
    "afrobeat": "World",
    "world": "World",
}

# Junk tags to ignore
_JUNK = {
    "female vocalists", "male vocalists", "seen live", "favourites",
    "favorites", "beautiful", "chill", "catchy", "cover", "instrumental",
    "acoustic", "american", "british", "australian", "english", "usa",
    "amazing", "love", "sexy", "party", "summer", "classic", "oldies",
    "mellow", "spanish",

    # platform / playlist / library noise
    "all", "miscellaneous: compilations", "vhs", "moja muzika",
    # labels & imprints
    "nyege nyege tapes", "anjunabeats",
    # instruments and credits, not genres
    "piano", "guitar", "xylophone", "composer",
    # place names
    "los angeles",
    # country / nationality tags
    "ukraine", "ukrainian", "iceland", "icelandic", "croatia", "croatian",
    "serbia", "serbian", "slovenia", "ex-yu", "france", "french",
    "german", "germany", "sweden", "swedish", "netherlands",
    "uk", "united states", "mexico", "colombia", "uganda", "korean",
}